<?php
namespace jakharbek\topics\controllers;

use Yii;
use yii\base\Controller;
use yii\helpers\ArrayHelper;

class TopicsController extends Controller{
    public function actions()
    {
        return ArrayHelper::merge(parent::actions(),[
            'index' => [
                'class' => 'jakharbek\topics\actions\TopicsAction'
            ]
        ]); // TODO: Change the autogenerated stub
    }
}